### ISSUE TITLE
Not able to vote on first click

### ISSUE THREAD

**Issue by Abydin** [plebbit/plebbit-react#258]
AssertionError [ERR_ASSERTION]: publishVote publishVoteOptions.vote not 1, 0 or -1

![Image](https://user-images.githubusercontent.com/36446984/233766847-bee67b11-1d88-4e62-aee7-3486c7c9cc3f.png)

**Comment by Poeticmind2475** [comment]
Hello

**Comment by estebanabaroa** [comment]
![Screenshot 2023-04-28 at 23-42-23 is there a correlation between anime watching and autism](https://user-images.githubusercontent.com/90033261/235270393-7ad38152-38d4-4576-b52c-0313ece488c9.png)

After the pending reply is posted, the text area of the comment should be reset.
