### ISSUE TITLE
RSS

### ISSUE THREAD

**Issue by sjehuda** [plebbit/plebbit-react#331]
Syndication web feeds are missing.

Preferably in the form or Atom and Json, and also in ActivityStreams (see GNU social).
```[tasklist]
### Tasks
- [ ] Atom Syndication
- [ ] ActivityStreams
- [ ] ￼JSON Feed
```

```[tasklist]
### Tasks
```

**Comment by sjehuda** [comment]
RSS is not dynamic.

It is as dynamic as the HTML that plebbit-react produces.

plebbit-react produces and HTML file, and an XML file (RSS).

RSS is a file produced by the server, not the client.

Feed Readers are the clients that read the RSS files.

e.g. Take Mastodon as an example

***@***.*** (HTML)
***@***.*** (RSS)

**Comment by sjehuda** [comment]
e.g. Take Mastodon as an example

https://mastodon.work/@Abaroa (HTML)
https://mastodon.work/@Abaroa.rss (RSS)

**Comment by estebanabaroa** [comment]
> RSS is not dynamic.

yes it is

> https://mastodon.work/@Abaroa (HTML)
> https://mastodon.work/@Abaroa.rss (RSS)

Those are 2 different (dynamic) pages.

If you go to https://plebbit-test.netlify.app/#/p/reddit-screenshots.eth/c/QmfKERsY6htXuL3wxXiVnSUT73HwxsuT49ZzrB5GjHg76K can see that it's a single page application, it only makes a request to the path `/` the rest of the URL is a hash router `#/p/reddit-screenshots.eth/c/QmfKERsY6htXuL3wxXiVnSUT73HwxsuT49ZzrB5GjHg76K` which is not sent to any server.

This repo has no server that can serve 2 different dynamic pages such as `/@Abaroa` or `/@Abaroa.rss`, it only has static HTML, ie a single page application.

It's possible to build an RSS server for plebbit but it would not be in this repo, it would probably be better suited for https://github.com/plebbit/plebbit-cli or be its own project.

**Comment by sjehuda** [comment]
I didn't take the hashes into consideration.

1) The h-entry can be a solution.

See http://microformats.org/wiki/h-entry

2) We can also scrape data into Atom or RSS feed using Javascript.

```js
mainTitle = document.querySelector('div.css-1pxyufv > div').textContent; // Healling Our Troubled Information Ecosystem
subTitle = document.querySelector('div.chakra-skeleton.css-1qgn8gy > a').textContent; // p/censorship-watch.eth
mainPost = document.querySelector('div.css-1pxyufv > div').textContent; // Healling Our Troubled Information Ecosystem
for (const item of document.querySelectorAll('.css-1lv53r0')) {
  entryTitle = item.querySelector('.css-1jj2vpp').textContent; // 18 days ago
  entryContent =  item.querySelector('p').textContent; // zz
}

...

// Generate Atom feed
```

https://plebbit-test.netlify.app/#/p/censorship-watch.eth/c/QmVXqaAY6SjcanGSuTTA8WTqfZLrHdozYJB7nFwN9nVqg8

**Comment by sjehuda** [comment]
Please ignore # 2

After wegenerate a feed, we have to have a source to request data from, which we don't
